#!/bin/bash

# Instructions copied from
# http://wiki.gfdl.noaa.gov/index.php/MOM6_setup_instructions#Compiling_with_the_Intel_compiler
platform=$1
do_non_sym=0
do_sym=1

# Shared code
mkdir -p build/shared.$platform.repro/
(cd build/shared.$platform.repro/; pwd; \
rm -f path_names; ../../bin/list_paths ../../src/FMS; \
mv path_names path_names.orig; egrep -v "atmos_ocean_fluxes|coupler_types|coupler_util" path_names.orig > path_names; \
../../bin/mkmf -t ../../src/mkmf/templates/$platform.mk -p libfms.a -c "-Duse_libMPI -Duse_netCDF -DSPMD -DLAND_BND_TRACERS" path_names)
(cd build/shared.$platform.repro/; source ../../build/env/${platform}; make FC=gfortran NETCDF=4 REPRO=1 libfms.a)

mkdir -p build/shared.$platform.debug/
(cd build/shared.$platform.debug/; \
rm -f path_names; ../../bin/list_paths ../../src/FMS; \
mv path_names path_names.orig; egrep -v "atmos_ocean_fluxes|coupler_types|coupler_util" path_names.orig > path_names; \
../../bin/mkmf -t ../../src/mkmf/templates/$platform.mk -p libfms.a -c "-Duse_libMPI -Duse_netCDF -DSPMD -DLAND_BND_TRACERS" path_names)
(cd build/shared.$platform.debug/; source ../../build/env/$platform; make FC=gfortran NETCDF=4 DEBUG=1  libfms.a)

if [ $do_non_sym == 1 ]; then
# MOM6 so code
mkdir -p build/MOM6_solo.$platform.repro/
(cd build/MOM6_solo.$platform.repro/; \
rm -f path_names; ../../bin/list_paths ../../src/MOM6/{config_src/dynamic,config_src/solo_driver,src/*,src/*/*}/ ../../src/FMS ;\
../../bin/mkmf -t ../../src/mkmf/templates/$platform.mk -p MOM6 -c "-Duse_libMPI -Duse_netCDF -DSPMD -DLAND_BND_TRACERS -Duse_AM3_physics" path_names; \
ln -sf ../shared.$platform.repro/*.{o,mod} .)
(cd build/MOM6_solo.$platform.repro/; source ../../build/env/$platform; make FC=gfortran NETCDF=4 REPRO=1 -j 8)

   
mkdir -p build/MOM6_solo.$platform.debug/
(cd build/MOM6_solo.$platform.debug/; \
rm -f path_names; ../../bin/list_paths ../../src/MOM6/{config_src/dynamic,config_src/solo_driver,src/*,src/*/*}/ ../../src/FMS  ; \
../../bin/mkmf -t ../../src/mkmf/templates/$platform.mk -p MOM6 -c "-Duse_libMPI -Duse_netCDF -DSPMD -DLAND_BND_TRACERS -Duse_AM3_physics" path_names; \
ln -sf ../shared.$platform.repro/*.{o,mod} .)
(cd build/MOM6_solo.$platform.debug/; source ../../build/env/$platform; make FC=gfortran NETCDF=4 DEBUG=1 -j 8)
fi

if [ $do_sym == 1 ]; then
# MOM6+SIS2 code
mkdir -p build/MOM6_solo.$platform.symmetric.repro/
(cd build/MOM6_solo.$platform.symmetric.repro/; \
rm -f path_names; ../../bin/list_paths ../../src/MOM6/{config_src/dynamic_symmetric,config_src/solo_driver,src/*,src/*/*}/ ../../src/FMS  ; \
../../bin/mkmf -t ../../src/mkmf/templates/$platform.mk -p MOM6 -c "-Duse_libMPI -Duse_netCDF -DSPMD -DLAND_BND_TRACERS -Duse_AM3_physics" path_names; \
ln -sf ../shared.$platform.repro/*.{o,mod} .)
(cd build/MOM6_solo.$platform.symmetric.repro/; source ../../build/env/$platform; make FC=gfortran NETCDF=4 REPRO=1 -j 8)

mkdir -p build/MOM6_solo.$platform.symmetric.debug/
(cd build/MOM6_solo.$platform.symmetric.debug/; \
rm -f path_names; ../../bin/list_paths ../../src/MOM6/{config_src/dynamic_symmetric,config_src/solo_driver,src/*,src/*/*}/ ../../src/FMS/  ; \
../../bin/mkmf -t ../../src/mkmf/templates/$platform.mk -p MOM6 -c "-Duse_libMPI -Duse_netCDF -DSPMD -DLAND_BND_TRACERS -Duse_AM3_physics" path_names; \
ln -sf ../shared.$platform.repro/*.{o,mod} .)
(cd build/MOM6_solo.$platform.symmetric.debug/; source ../../build/env/$platform; make FC=gfortran NETCDF=4 DEBUG=1 -j 8)
fi
